'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {content} from '@/lib/content';
import {event,dateLabel,languages,Language} from '@/lib/config';
const Context=createContext<{lang:Language,setLang:(l:Language)=>void}>({lang:'en',setLang:()=>{}});
export const useLanguage=()=>useContext(Context);
export function Site({children}:{children:ReactNode}){
 const [lang,setLanguage]=useState<Language>('en');const path=usePathname();
 useEffect(()=>{const saved=localStorage.getItem('wedding-language');if(languages.includes(saved as Language))setLanguage(saved as Language);else fetch('/api/invitation').then(r=>r.ok?r.json():null).then(d=>{if(d?.language)setLanguage(d.language)}).catch(()=>{});},[]);
 useEffect(()=>{document.documentElement.lang=lang},[lang]);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:0},{opacity:1}],{duration:700,easing:'ease-out'});observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('main section:not(.rsvp) h1,main section:not(.rsvp) h2,main section:not(.rsvp) .photo-frame').forEach(e=>observer.observe(e));return()=>observer.disconnect()},[path]);
 function setLang(l:Language){setLanguage(l);localStorage.setItem('wedding-language',l)}
 const t=content[lang];return <Context.Provider value={{lang,setLang}}><a className="skip" href="#main">{t.skip}</a><header><nav aria-label="Main">{['/','/love-story','/details','/faq','/rsvp'].map((p,i)=><Link key={p} href={p} aria-current={path===p?'page':undefined}>{t.nav[i]}</Link>)}</nav><div className="languages" aria-label="Language">{languages.map((l,i)=><button key={l} aria-label={['English','Norsk','Lietuvių'][i]} aria-pressed={lang===l} onClick={()=>setLang(l)}>{['EN','NO','LT'][i]}</button>)}</div></header><main id="main">{children}</main><footer><Link href="/">← {t.back}</Link></footer></Context.Provider>
}
export function Monogram(){return <div className="monogram" aria-label="M and D"><span>M</span><span>D</span></div>}
export function Contact(){return <address><a href={'mailto:'+event.email}>{event.email}</a><br/><a href={'tel:'+event.phone}>{event.phoneDisplay}</a></address>}
export function Frame({photo,shape='oval',alt}:{photo:string,shape?:'oval'|'rectangle'|'horizontal'|'tilted',alt:string}){return <div className={'photo-frame '+shape}><img className="photo" src={'/assets/'+photo} alt={alt}/><img className="frame" src={'/assets/'+(shape==='oval'?'oval-frame.png':shape==='horizontal'?'horizontal-frame.png':shape==='tilted'?'tilted-frame.png':'rectangle-frame-large.png')} alt=""/></div>}
function Countdown(){const {lang}=useLanguage();const [now,setNow]=useState<number|null>(null);useEffect(()=>{setNow(Date.now());const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const n=Math.max(0,Math.floor((Date.parse(event.weddingStart)-(now??Date.parse(event.weddingStart)))/1000));return <div className="countdown" aria-label={content[lang].forever}>{[Math.floor(n/86400),Math.floor(n/3600)%24,Math.floor(n/60)%60,n%60].map((v,i)=><div key={i}><span>{now===null?'—':String(v).padStart(2,'0')}</span><small>{content[lang].units[i]}</small></div>)}</div>}
export function Home(){const {lang}=useLanguage();const t=content[lang];return <><section className="hero"><div><h1><span>Marthe</span><em>{t.and}</em><span>Deivi</span></h1><p>{t.married}<br/><strong>04.09.27</strong></p></div></section><section className="invitation-section"><div className="curtain"><div className="curtain-copy"><h2>{lang==='nb'?<>Kjære<br/>familie og venner,</>:t.dear}</h2><p>{t.invitation}</p><Monogram/></div></div><Countdown/><h2 className="until">{t.until}<em>{t.forever}</em></h2></section><section className="envelope-section"><div className="envelope"><img src="/assets/envelope.png" alt=""/><div className="envelope-photo"><Frame photo="couple-wedding.jpg" shape="rectangle" alt="Marthe and Deivi embracing"/></div></div><p className="script">{t.celebrate}</p><Link className="rsvp-callout" href="/rsvp">{t.kindly}<small>{t.by} {dateLabel(lang)}</small></Link><img className="swans" src="/assets/blue-swans.png" alt=""/></section></>}
export function Story(){const {lang}=useLanguage();const t=content[lang];return <section className="story floral"><h1><em>{t.our}</em>{t.story}</h1><div className="story-content"><p>{t.storyParagraphs[0]}</p><Frame photo="couple-early.jpg" alt="Marthe and Deivi in the early years"/>{t.storyParagraphs.slice(1).map((p,i)=><div key={i}><p>{p}</p>{i===2&&<Frame photo="rings-photo.jpg" shape="horizontal" alt="Wedding rings and joined hands"/>}</div>)}<Monogram/></div></section>}
function External({kind,label}:{kind:keyof typeof event.links,label:string}){const {lang}=useLanguage();const url=event.links[kind];return url?<a className="outline" href={url} rel="noreferrer">{label}</a>:<span className="unavailable"><button className="outline" disabled>{label}</button><small>{content[lang].unavailable}</small></span>}
export function Details(){const {lang}=useLanguage();const t=content[lang];return <><section className="date-venue floral"><h1>{t.date}<em>{t.and}</em>{t.venue}</h1><h2>{dateLabel(lang,event.weddingDate)}</h2><Frame photo="venue-photo.jpg" shape="rectangle" alt="Villa 9 Vėjai and its grounds"/><h3>Villa 9 Vejai<br/>Girininkai, Lithuania</h3><p>{t.venueText}</p><External kind="map" label={t.map}/></section><section className="travel"><h2>{t.travel}</h2><h3 className="script">{t.car}</h3><p>Knygnešio P. Varkalos g. 44</p><p>{t.parking}</p><h3 className="script">{t.travelers}</h3>{t.travelParagraphs.map(p=><p key={p}>{p}</p>)}<h3 className="script">{t.speeches}</h3><p>{t.speechText}</p><a href={'tel:'+event.toastmasterPhone}>+47 948 96 863</a></section><section className="timeline floral"><h2>{t.timeline}</h2>{t.weekend.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}<img className="flourish" src="/assets/flourish.svg" alt=""/><p className="smallcaps">{t.more}</p></section><section className="accommodations"><h2>{t.accommodation}</h2><div className="stay-grid"><article><h3 className="script">{t.kaunas}</h3><p className="smallcaps">{lang==='en'?'3–4 September 2027':lang==='nb'?'3.–4. september 2027':'2027 m. rugsėjo 3–4 d.'}</p>{t.kaunasText.map(p=><p key={p}>{p}</p>)}</article><article><h3 className="script">Villa 9 Vejai</h3><p className="smallcaps">{lang==='en'?'4–5 September 2027':lang==='nb'?'4.–5. september 2027':'2027 m. rugsėjo 4–5 d.'}</p><p>{t.venueStay}</p><p>{t.questions}</p><External kind="venue" label={t.website}/></article></div><p>{t.accommodationNote}</p></section><section className="dress floral"><h2>{t.dress}<em>{t.code}</em></h2><h3>{t.formal}</h3>{t.dressText.map(p=><p key={p}>{p}</p>)}<div className="palette" aria-label="Color inspiration">{['#7d894a','#972626','#fcc0c5'].map(c=><span key={c} style={{background:c}}/>)}</div></section><section className="gift"><h2>{t.gift}<em>{t.registry}</em></h2><p>{t.registryText}</p><External kind="registry" label={t.viewRegistry}/></section></>}
export function FAQ(){const {lang}=useLanguage();const t=content[lang];return <section className="faq floral"><h1>FAQ</h1><Frame photo="bouquet-photo.jpg" shape="tilted" alt="Wedding bouquet detail"/>{t.faq.map(([q,a],i)=><article key={q}><h2>{q}</h2><p>{a}</p>{i===2&&<Contact/>}</article>)}</section>}
