import {NextRequest} from 'next/server';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {demo,insertInvitation,listInvitations,updateInvitation} from '@/lib/db';
import {Invitation,AppError,applyResponse,totals} from '@/lib/model';
import {body,errorResponse,guard,hashToken,json,newToken,requireAdmin} from '@/lib/security';
const schema=z.object({id:z.uuid().optional(),version:z.number().int().optional(),label:z.string().trim().min(1).max(150),language:z.enum(['en','nb','lt']),contact:z.string().trim().max(200),guests:z.array(z.object({id:z.uuid().optional(),name:z.string().trim().max(150),companion:z.boolean()})).min(1).max(30)});
export async function GET(){try{await requireAdmin();const invitations=await listInvitations();return json({invitations,totals:totals(invitations),demo:demo()})}catch(e){return errorResponse(e)}}
export async function POST(req:NextRequest){try{await requireAdmin();await guard(req,'admin-create');const p=schema.safeParse(await body(req));if(!p.success)throw new AppError('validation');const data=p.data;if(data.guests.some(g=>!g.name&&!g.companion))throw new AppError('validation');const now=new Date().toISOString();const inv:Invitation={id:randomUUID(),label:data.label,language:data.language,contact:data.contact,guests:data.guests.map(g=>({id:randomUUID(),name:g.name,companion:g.companion,attendance:null,diet:null,dietDetails:'',hotel:null,overnight:null})),message:'',version:0,createdAt:now,updatedAt:now,submittedAt:null,revoked:false,lastRequestId:null};const token=newToken();await insertInvitation(inv,hashToken(token));return json({invitation:inv,link:(process.env.APP_ORIGIN||new URL(req.url).origin)+'/invite#'+token})}catch(e){return errorResponse(e)}}
export async function PATCH(req:NextRequest){try{await requireAdmin();await guard(req,'admin-update');const data=await body(req);if(!z.uuid().safeParse(data.id).success)throw new AppError('validation');if(data.action==='response'){const inv=await updateInvitation(data.id,'id',i=>applyResponse(i,data.response,true));return json({invitation:inv})}let token:string|undefined;if(data.action==='rotate')token=newToken();const inv=await updateInvitation(data.id,'id',i=>{if(data.version!==i.version)throw new AppError('conflict',409);if(data.action==='revoke')return {...i,revoked:true,version:i.version+1,updatedAt:new Date().toISOString()};if(data.action==='rotate')return {...i,revoked:false,version:i.version+1,updatedAt:new Date().toISOString()};const p=schema.safeParse(data);if(!p.success)throw new AppError('validation');const g=p.data.guests;if(new Set(g.filter(g=>g.id).map(g=>g.id)).size!==g.filter(g=>g.id).length||g.some(g=>(g.id&&!i.guests.some(old=>old.id===g.id))||(!g.name&&!g.companion)))throw new AppError('validation');return {...i,label:p.data.label,language:p.data.language,contact:p.data.contact,guests:g.map(g=>({...i.guests.find(old=>old.id===g.id)??{id:randomUUID(),attendance:null,diet:null,dietDetails:'',hotel:null,overnight:null},name:g.name,companion:g.companion})),version:i.version+1,lastRequestId:null,updatedAt:new Date().toISOString()};},token?hashToken(token):undefined);return json({invitation:inv,...(token?{link:(process.env.APP_ORIGIN||new URL(req.url).origin)+'/invite#'+token}:{})})}catch(e){return errorResponse(e)}}
