import { Language } from './config';
export const content = {
en: {
nav:['Home','Love Story','Details','FAQ','RSVP'], and:'and', married:'are getting married', dear:'Dear Family & Friends,', invitation:'We invite you to join us on our wedding day. Surrounded by our closest loved ones, we\'ll say "I do" and begin a new chapter together.', until:'until our', forever:'forever begins', units:['Days','Hours','Minutes','Seconds'], kindly:'Kindly RSVP here', by:'by', celebrate:"We can't wait to celebrate with you.", our:'our', story:'Love Story', storyParagraphs:[
'If there’s one thing our story has taught us, it’s that a little curiosity, and some questionable flirting, can change everything.',
'Soon, we were best friends, finding every excuse to spend time together despite living on opposite sides of our hometown. Later, Bergen became our home. Deivi moved for work, and Marthe followed. Those years gave us lifelong friendships, new experiences, and more than a few memorable nights out.',
'Eventually, we returned to our hometown to focus on education and build our future. Through every change, we’ve held onto the same belief: when a light goes out in your home, you change the bulb; you don’t buy a new house. We care for what we’ve built, and for the people around us.',
'Looking back, it’s funny to think that all of this began with a glance across a cafeteria. Through thick and thin, we’ve grown together, and we’re excited for everything still to come.',
'Now, as we look ahead to this next chapter, we’re filled with gratitude for the journey that brought us here and excitement for everything still to come.',
'Most of all, we’re grateful to share this day with the people who have been part of our story from the very beginning, middle and end.'],
date:'Date',venue:'Venue',venueText:'Both our ceremony and reception will take place at Villa 9 Vejai. We kindly ask guests to arrive 30 minutes before the ceremony begins.',map:'View on Map',unavailable:'Link to follow',travel:'How to Get There',car:'By car',parking:'Complimentary parking is available at both the ceremony and reception locations.',travelers:'Traveling guests',travelParagraphs:[
'The easiest route is to fly from Oslo to Vilnius. From Vilnius Airport, travel to Vilnius train station, then take the train to Kaunas. The train ride takes about one hour.',
'We recommend arriving on Friday, 3 September, and staying at a hotel in Kaunas before the wedding.',
'The wedding venue is about 20 minutes from Kaunas by car. We recommend a taxi or ride service, or a rental car if you plan to explore the area.',
'Please book your travel early. You’re welcome to contact us for help with travel plans, hotels or any other questions.'],speeches:'Speeches',speechText:'Would you like to share a few words or prepare a surprise? Please contact our toastmaster, Mathias Krohn, to arrange speeches, toasts, or other contributions to the evening.',timeline:'Timeline',weekend:[
['Friday, 3 September | Welcome Dinner','For guests travelling to Lithuania, we’ll meet at a restaurant in Kaunas for a relaxed dinner. It’s a chance to catch up, meet everyone and start the weekend together.'],
['Saturday, 4 September | Ceremony & Celebration','We’ll gather at 9 Vėjai for the ceremony, followed by dinner, music and a wedding party that lasts into the night.'],
['Sunday, 5 September | Farewell Barbecue','After a slow morning, we’re planning a casual barbecue with our guests before we say goodbye. Those travelling home on Sunday can leave whenever it suits their plans.']],more:'More details, including times and locations, will follow.',accommodation:'Accommodations',kaunas:'Stay in Kaunas',kaunasText:['We’re exploring hotel options in Kaunas and hope to arrange a group rate for guests arriving the day before the wedding.','Once we’ve received your RSVPs, we’ll have a better idea of numbers and share an update with those joining us.'],venueStay:'Set in the countryside near Kaunas, Villa 9 Vėjai is where we’ll celebrate and stay together. We’ve arranged and covered your overnight stay.',questions:'Please contact us if you have any questions.',website:'Visit Website',accommodationNote:'Please let us know in your RSVP if you’ll need accommodation in Kaunas on 3–4 September. This will help us explore a group rate. We’ll share hotel options and travel updates once arrangements are confirmed.',dress:'Dress',code:'code',formal:'Formal Attire',dressText:['As we gather to celebrate this special day, we invite our guests to dress in formal attire.','Our color palette is provided below for inspiration, though your presence is what matters most.'],gift:'Gift',registry:'registry',registryText:"Your presence at our wedding is the greatest gift of all. For friends and family who have asked, we've created a registry with a few things we'd love for our home and future together.",viewRegistry:'View Registry',faq:[['Can I bring a plus one?','Please refer to your invitation for details regarding additional guests.'],['Can i wear white?','No.'],['Who should I contact if I have questions?','For travel, accommodation, or wedding questions, please contact us.']],rsvpIntro:'Please let us know if you can celebrate with us by',contactText:"For any questions regarding travel, accommodations, or wedding details, please don't hesitate to contact us.",back:'back',skip:'Skip to content'
},
nb: {
nav:['Hjem','Vår historie','Detaljer','Spørsmål','Svar'],and:'og',married:'skal gifte seg',dear:'Kjære familie og venner,',invitation:'Vi inviterer dere til å feire bryllupsdagen vår med oss. Omgitt av våre nærmeste sier vi «ja» og begynner et nytt kapittel sammen.',until:'til vår',forever:'begynnelse på for alltid',units:['Dager','Timer','Minutter','Sekunder'],kindly:'Svar på invitasjonen her',by:'innen',celebrate:'Vi gleder oss til å feire med dere.',our:'vår',story:'Kjærlighetshistorie',storyParagraphs:[
'Hvis historien vår har lært oss én ting, er det at litt nysgjerrighet og noen tvilsomme flørteforsøk kan forandre alt.',
'Snart var vi bestevenner og fant enhver unnskyldning for å være sammen, selv om vi bodde på hver vår side av hjembyen. Senere ble Bergen hjemmet vårt. Deivi flyttet for å jobbe, og Marthe fulgte etter. Disse årene ga oss vennskap for livet, nye opplevelser og mer enn noen få minneverdige kvelder ute.',
'Etter hvert vendte vi tilbake til hjembyen for å prioritere utdanning og bygge fremtiden vår. Gjennom alle forandringene har vi holdt fast ved det samme: Når en lyspære hjemme slukker, bytter man pæren; man kjøper ikke et nytt hus. Vi tar vare på det vi har bygget, og på menneskene rundt oss.',
'Når vi ser tilbake, er det morsomt å tenke på at alt begynte med et blikk på tvers av en kantine. Gjennom tykt og tynt har vi vokst sammen, og vi gleder oss til alt som venter.',
'Nå som vi ser frem mot neste kapittel, er vi fylt av takknemlighet for reisen som har ført oss hit, og glede over alt som ligger foran oss.',
'Mest av alt er vi takknemlige for å dele denne dagen med menneskene som har vært en del av historien vår fra begynnelsen, gjennom midten og til slutten.'],
date:'Dato',venue:'Sted',venueText:'Både vielsen og festen finner sted på Villa 9 Vejai. Vi ber gjestene om å komme 30 minutter før vielsen begynner.',map:'Vis på kart',unavailable:'Lenke kommer',travel:'Slik kommer du deg dit',car:'Med bil',parking:'Gratis parkering er tilgjengelig ved både vielsen og festen.',travelers:'Tilreisende gjester',travelParagraphs:[
'Den enkleste ruten er å fly fra Oslo til Vilnius. Fra Vilnius lufthavn reiser du til togstasjonen i Vilnius og tar toget videre til Kaunas. Togturen tar omtrent én time.',
'Vi anbefaler å ankomme fredag 3. september og bo på hotell i Kaunas før bryllupet.',
'Bryllupsstedet ligger omtrent 20 minutter fra Kaunas med bil. Vi anbefaler taxi eller en kjøretjeneste, eller leiebil hvis du vil utforske området.',
'Bestill gjerne reisen tidlig. Ta kontakt hvis du ønsker hjelp med reiseplaner, hoteller eller andre spørsmål.'],speeches:'Taler',speechText:'Vil du si noen ord eller forberede en overraskelse? Kontakt toastmasteren vår, Mathias Krohn, for å avtale taler, skåler eller andre innslag i løpet av kvelden.',timeline:'Helgens program',weekend:[
['Fredag 3. september | Velkomstmiddag','For gjester som reiser til Litauen, møtes vi på en restaurant i Kaunas til en avslappet middag. Det blir en anledning til å prate, bli kjent og starte helgen sammen.'],
['Lørdag 4. september | Vielse og feiring','Vi samles på 9 Vėjai til vielsen, etterfulgt av middag, musikk og bryllupsfest til langt på natt.'],
['Søndag 5. september | Avskjedsgrilling','Etter en rolig morgen planlegger vi en uformell grillfest med gjestene før vi tar farvel. De som reiser hjem på søndag, kan dra når det passer med planene deres.']],more:'Flere detaljer, inkludert tidspunkter og steder, kommer senere.',accommodation:'Overnatting',kaunas:'Bo i Kaunas',kaunasText:['Vi undersøker hotellmuligheter i Kaunas og håper å få en gruppepris for gjester som kommer dagen før bryllupet.','Når vi har mottatt svarene deres, vet vi mer om antallet og deler en oppdatering med dem som blir med.'],venueStay:'Villa 9 Vėjai ligger på landet nær Kaunas. Her skal vi feire og overnatte sammen. Vi har ordnet og dekket overnattingen deres.',questions:'Ta kontakt hvis dere har spørsmål.',website:'Besøk nettsiden',accommodationNote:'Gi oss beskjed i svaret om dere trenger overnatting i Kaunas 3.–4. september. Dette hjelper oss å undersøke en gruppepris. Vi deler hotellalternativer og reiseinformasjon når ordningene er bekreftet.',dress:'Antrekk',code:'for dagen',formal:'Formelt antrekk',dressText:['Når vi samles for å feire denne spesielle dagen, inviterer vi gjestene til å kle seg i formelt antrekk.','Fargepaletten nedenfor er ment som inspirasjon, men det viktigste er at dere er der.'],gift:'Gaver',registry:'og ønskeliste',registryText:'At dere er med på bryllupet vårt, er den største gaven. For venner og familie som har spurt, har vi laget en ønskeliste med noen ting til hjemmet og fremtiden vår sammen.',viewRegistry:'Se ønskelisten',faq:[['Kan jeg ta med en ledsager?','Se invitasjonen din for informasjon om ekstra gjester.'],['Kan jeg gå i hvitt?','Nei.'],['Hvem kontakter jeg hvis jeg har spørsmål?','Ta kontakt med oss om reise, overnatting eller bryllupet.']],rsvpIntro:'Gi oss beskjed om du kan feire med oss innen',contactText:'Ta gjerne kontakt med oss hvis du har spørsmål om reise, overnatting eller bryllupsdetaljer.',back:'tilbake',skip:'Hopp til innhold'
},
lt: {
nav:['Pradžia','Mūsų istorija','Informacija','DUK','Atsakymas'],and:'ir',married:'tuokiasi',dear:'Miela šeima ir draugai,',invitation:'Kviečiame jus būti kartu mūsų vestuvių dieną. Apsupti artimiausių žmonių, ištarsime „taip“ ir kartu pradėsime naują gyvenimo skyrių.',until:'iki mūsų',forever:'amžinybės pradžios',units:['Dienos','Valandos','Minutės','Sekundės'],kindly:'Prašome atsakyti čia',by:'iki',celebrate:'Nekantraujame švęsti kartu su jumis.',our:'mūsų',story:'Meilės istorija',storyParagraphs:[
'Jei mūsų istorija ko nors išmokė, tai to, kad truputis smalsumo ir šiek tiek abejotino flirto gali pakeisti viską.',
'Netrukus tapome geriausiais draugais ir rasdavome bet kokią progą praleisti laiką kartu, nors gyvenome skirtingose gimtojo miesto pusėse. Vėliau mūsų namais tapo Bergenas. Deivi persikėlė dėl darbo, o Marthe atvyko paskui jį. Tie metai padovanojo draugysčių visam gyvenimui, naujų patirčių ir ne vieną įsimintiną vakarą.',
'Galiausiai grįžome į gimtąjį miestą mokytis ir kurti savo ateities. Per visas permainas laikėmės to paties įsitikinimo: kai namuose užgęsta lemputė, ją pakeiti, o ne perki naują namą. Rūpinamės tuo, ką sukūrėme, ir žmonėmis šalia mūsų.',
'Žvelgiant atgal, smagu pagalvoti, kad viskas prasidėjo nuo žvilgsnio per valgyklą. Ir gerais, ir sunkiais laikais augome kartu ir su džiaugsmu laukiame visko, kas dar prieš akis.',
'Dabar, laukdami kito skyriaus, jaučiame dėkingumą už kelią, atvedusį mus iki čia, ir džiaugsmą dėl visko, kas dar laukia.',
'Labiausiai esame dėkingi, kad šia diena galime dalytis su žmonėmis, kurie buvo mūsų istorijos dalis nuo pat pradžios, per jos vidurį ir iki pabaigos.'],
date:'Data',venue:'Vieta',venueText:'Ir ceremonija, ir šventė vyks Villa 9 Vejai. Maloniai prašome svečių atvykti likus 30 minučių iki ceremonijos pradžios.',map:'Žiūrėti žemėlapyje',unavailable:'Nuoroda bus vėliau',travel:'Kaip atvykti',car:'Automobiliu',parking:'Nemokamos stovėjimo vietos yra prie ceremonijos ir šventės vietų.',travelers:'Atvykstantiems svečiams',travelParagraphs:[
'Paprasčiausia skristi iš Oslo į Vilnių. Iš Vilniaus oro uosto vykite į Vilniaus geležinkelio stotį, o tada traukiniu į Kauną. Kelionė traukiniu trunka apie valandą.',
'Rekomenduojame atvykti penktadienį, rugsėjo 3 d., ir prieš vestuves apsistoti viešbutyje Kaune.',
'Vestuvių vieta yra maždaug už 20 minučių kelio automobiliu nuo Kauno. Rekomenduojame taksi ar pavėžėjimo paslaugas arba išsinuomoti automobilį, jei norėsite apžiūrėti apylinkes.',
'Prašome kelionę užsisakyti iš anksto. Susisiekite, jei reikia pagalbos planuojant kelionę, renkantis viešbutį ar turite kitų klausimų.'],speeches:'Kalbos',speechText:'Norėtumėte tarti kelis žodžius ar paruošti staigmeną? Susisiekite su mūsų vakaro vedėju Mathias Krohn, kad suderintumėte kalbas, tostus ar kitus vakaro pasirodymus.',timeline:'Savaitgalio programa',weekend:[
['Penktadienis, rugsėjo 3 d. | Pasitikimo vakarienė','Į Lietuvą atvykstantiems svečiams surengsime jaukią vakarienę Kauno restorane. Tai bus proga pasikalbėti, susipažinti ir kartu pradėti savaitgalį.'],
['Šeštadienis, rugsėjo 4 d. | Ceremonija ir šventė','Susirinksime 9 Vėjai ceremonijai, po kurios lauks vakarienė, muzika ir vestuvių šventė iki vėlumos.'],
['Sekmadienis, rugsėjo 5 d. | Atsisveikinimo kepsniai','Po ramaus ryto planuojame neformalius kepsnius su svečiais prieš atsisveikindami. Sekmadienį namo keliaujantys svečiai gali išvykti pagal savo planus.']],more:'Daugiau informacijos, įskaitant laikus ir vietas, pateiksime vėliau.',accommodation:'Nakvynė',kaunas:'Nakvynė Kaune',kaunasText:['Ieškome viešbučių Kaune ir tikimės sutarti dėl grupinės kainos svečiams, atvykstantiems dieną prieš vestuves.','Gavę jūsų atsakymus, geriau žinosime svečių skaičių ir pasidalysime naujienomis su prisijungsiančiais.'],venueStay:'Netoli Kauno, kaimo apsuptyje esanti Villa 9 Vėjai – vieta, kur švęsime ir nakvosime kartu. Jūsų nakvynę jau pasirūpinome ir apmokėjome.',questions:'Jei turite klausimų, susisiekite su mumis.',website:'Apsilankyti svetainėje',accommodationNote:'Atsakyme nurodykite, ar jums reikės nakvynės Kaune rugsėjo 3–4 d. Tai padės mums pasidomėti grupine kaina. Kai susitarimai bus patvirtinti, pasidalysime viešbučių pasiūlymais ir kelionės naujienomis.',dress:'Aprangos',code:'kodas',formal:'Oficiali apranga',dressText:['Susirinkus švęsti šią ypatingą dieną, kviečiame svečius rinktis oficialią aprangą.','Žemiau pateikta spalvų paletė skirta įkvėpimui, tačiau svarbiausia mums – jūsų dalyvavimas.'],gift:'Dovanų',registry:'sąrašas',registryText:'Jūsų dalyvavimas mūsų vestuvėse – didžiausia dovana. Draugams ir šeimai, kurie teiravosi, sudarėme sąrašą kelių dalykų mūsų namams ir bendrai ateičiai.',viewRegistry:'Peržiūrėti sąrašą',faq:[['Ar galiu atsivesti lydintį asmenį?','Informaciją apie papildomus svečius rasite savo kvietime.'],['Ar galiu vilkėti baltai?','Ne.'],['Į ką kreiptis, jei turiu klausimų?','Dėl kelionės, nakvynės ar vestuvių klausimų susisiekite su mumis.']],rsvpIntro:'Prašome pranešti, ar švęsite kartu su mumis, iki',contactText:'Jei turite klausimų dėl kelionės, nakvynės ar vestuvių, nedvejodami susisiekite su mumis.',back:'atgal',skip:'Pereiti prie turinio'
}
} satisfies Record<Language, unknown>;
