import {Pool} from 'pg';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync} from 'node:fs';
import path from 'node:path';
import {Invitation,AppError} from './model';
let pg:Pool|undefined;let local:DatabaseSync|undefined;
export const demo=()=>process.env.LOCAL_DEMO==='true';
function pool(){if(!process.env.DATABASE_URL)throw new AppError('setup',503);return pg??=new Pool({connectionString:process.env.DATABASE_URL,max:5,connectionTimeoutMillis:10000,statement_timeout:10000})}
function sqlite(){if(!demo())throw new AppError('setup',503);if(!local){mkdirSync(path.resolve('.data'),{recursive:true});local=new DatabaseSync(path.resolve(process.env.DEMO_DB_PATH||'.data/demo.sqlite'));local.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS invitations (id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, document TEXT NOT NULL); CREATE TABLE IF NOT EXISTS request_limits (key TEXT PRIMARY KEY, window_start INTEGER NOT NULL, hits INTEGER NOT NULL);')}return local}
export async function listInvitations():Promise<Invitation[]>{return demo()?(sqlite().prepare('SELECT document FROM invitations').all() as {document:string}[]).map(r=>JSON.parse(r.document)):(await pool().query('SELECT document FROM invitations ORDER BY updated_at DESC')).rows.map(r=>r.document)}
export async function findInvitation(hash:string):Promise<Invitation|null>{const row=demo()?sqlite().prepare('SELECT document FROM invitations WHERE token_hash=?').get(hash):(await pool().query('SELECT document FROM invitations WHERE token_hash=$1',[hash])).rows[0];return row?(typeof row.document==='string'?JSON.parse(row.document):row.document):null}
export async function insertInvitation(inv:Invitation,hash:string){if(demo())sqlite().prepare('INSERT INTO invitations VALUES(?,?,?)').run(inv.id,hash,JSON.stringify(inv));else await pool().query('INSERT INTO invitations(id,token_hash,document) VALUES($1,$2,$3)',[inv.id,hash,inv])}
export async function updateInvitation(key:string,by:'id'|'token_hash',fn:(inv:Invitation)=>Invitation,newHash?:string):Promise<Invitation>{
 if(demo()){const db=sqlite();db.exec('BEGIN IMMEDIATE');try{const row=db.prepare(`SELECT document FROM invitations WHERE ${by}=?`).get(key);if(!row)throw new AppError('invalid',404);const next=fn(JSON.parse(row.document as string));if(newHash)db.prepare('UPDATE invitations SET document=?,token_hash=? WHERE id=?').run(JSON.stringify(next),newHash,next.id);else db.prepare('UPDATE invitations SET document=? WHERE id=?').run(JSON.stringify(next),next.id);db.exec('COMMIT');return next}catch(e){db.exec('ROLLBACK');throw e}}
 const client=await pool().connect();try{await client.query('BEGIN');const row=(await client.query(`SELECT document FROM invitations WHERE ${by}=$1 FOR UPDATE`,[key])).rows[0];if(!row)throw new AppError('invalid',404);const next=fn(row.document);await client.query('UPDATE invitations SET document=$1, updated_at=now()'+(newHash?', token_hash=$3':'')+' WHERE id=$2',newHash?[next,next.id,newHash]:[next,next.id]);await client.query('COMMIT');return next}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
export async function rateLimit(key:string,max=50,window=60000){const now=Date.now();let hits:number;if(demo()){const db=sqlite();const r=db.prepare('INSERT INTO request_limits(key,window_start,hits) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET window_start=CASE WHEN window_start < ? THEN ? ELSE window_start END,hits=CASE WHEN window_start < ? THEN 1 ELSE hits+1 END RETURNING hits').get(key,now,now-window,now,now-window);hits=Number(r!.hits)}else{const r=await pool().query('INSERT INTO request_limits(key,window_start,hits) VALUES($1,$2,1) ON CONFLICT(key) DO UPDATE SET window_start=CASE WHEN request_limits.window_start < $3 THEN $2 ELSE request_limits.window_start END,hits=CASE WHEN request_limits.window_start < $3 THEN 1 ELSE request_limits.hits+1 END RETURNING hits',[key,now,now-window]);hits=r.rows[0].hits}if(hits>max)throw new AppError('rate',429)}
